language: go
go: 1.13.x
env:
  matrix:
  - GO111MODULE=on
  global:
  - secure: osNYfkSx054AvkElyf/OSuz1jQugETRR62V6NLUObUfCaY8E64a4YTypNqUA3/B9GpfmoXo7ibyRu3JfmXy6509AYrydYSICBhFqkItsPhs1aVKPwaaSBNMtIzxovF1lWvM/h+CYXGjIyroa0fOnTfEvLFK1a2iJSZ0Uj9L6PyYCovLjEfKLqtLWweJObLJ2VvRNmbcLYkcQazLzN5swT4eJGVwBtD8YwEaGWfPwS+l4ldx1RQIVPDAh1SXEfoR5XiVclOpQxiVniFHi25ivLvb3kIPj5I/jSTKCTNfUB1VUannfnw19BRs5na0nAmzLAkVdXqTM1IMqK3x8hyzRSsQuKuCwca0Z2sSQ+o8gRUv09laUw2Q9xP/r4jrTh8SPFCif65o6kMFIaleVUtWscaD+YlhQ9G7233oKq0qkwxn9njOObg4ye/wAGwA1qXuvnYI/sX73cDUgqYhWGU3TqE++jjmKN/2N2YUWgM25sJcvjMCYa69vQVk4vJLRa0wPeL1WwFxMrUZdienfCKgUUe9TGbw1sXF3wS5VBz+9PuGLgAOroMiL8qVWXbebJRtzu9dh/VFxb/boKzkeOjWOMzZyJB0C/GvPrZlbawHdWBwD56u0yiCbFpjpSip6pfi8YcpYqlYp5w42Q+uA+mJkpd5GJKQDShe7a1a7tdevbKY=
  - secure: pnJjw0THHnDhLnTBf1Jhv5IzEx50NzTCUsQz47kuV7pQmqXHBLO3wLdgKDOIljC+ImUW4S/+FL822G172Fisvc33aMgsOvDr8CRSV+j5as2Fu196WYUWZ1Lx+oOB60joNQdAg7u7IATB4bKFpyNB09y+fBYsRDe2pORHnabsJopB90sYeFr9DYCwNXPw0DX2sY4Cp6jvjU3/NpyAiq0zy/pHOZbYA3Gdiyekc/7u4t4UqQQ+QA4GBopxyKg4hCU7aZe98OqHiGLdwXnJ6j7eW7U28IkOyE5A7Ma4SzMHl7lzxbB9OM9HebKaS1qJENr+pRQWweS6xKUWMwtIDW+cu7SpMNQFIH6ZreZzY9SmzL3sIrvDc6mPLm6vygK2y4Vri9M+rnNY1tNZSBUFQ42t8tAQyoswI64s03mUyX7MVK/R0ExNj82n0oZyWEjWlhVumy1elZD09oLgKyaELlOwdfmC94Q0ArmT8S368qLvjxj+G08WzeMiRVOaddB1sozIxu5AFJdP6HBy0LP4VSrUC0nT475xxn4EpZdSswn0DDPdyi8W858oGgnTXcoNix2evH5mciDoZIgphy9i6VUbi+YT1VajgHHQoRt9XMtB4bJWpi6KYQ1d33wofa4+RpkTgGSYXxlc2NOuY2GKKkkJ8QuL/2ygQbnOZTuGXgp8UPc=
notifications:
  email:
    recipients:
    - newfarry@126.com
    on_success: always
addons:
  apt:
    packages:
    - snapcraft
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && docker login -u=openiothub -p="$DOCKER_PASSWORD"
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
- test -n "$TRAVIS_TAG" && rm snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
before_install:
- openssl aes-256-cbc -K $encrypted_cb9005112845_key -iv $encrypted_cb9005112845_iv
  -in snap.login.enc -out snap.login -d
